language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - /.*/

notifications:
  email: false

services:
  - mongodb

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
